Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"
  config.vm.synced_folder "./confs", "/vagrant_shared"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "asekkakS" do |server|
    server.vm.hostname = "asekkakS"

    server.vm.network "private_network",
      ip: "192.168.56.110"

    server.vm.provision "shell",
      path: "./scripts/server.sh"

  end

end