Vagrant.configure("2") do |config|
    username = 'asekkak'
    config.vm.synced_folder "./confs", "/vagrant_shared"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  
    config.vm.define "#{username}S" do |server|
      server.vm.hostname = "#{username}S"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "#{username}S"
      end
  
      server.vm.box = "bento/debian-12"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provision "shell", path: "./scripts/server.sh", args: ['192.168.56.110']
    end
  
    config.vm.define "#{username}SW" do |worker|
      worker.vm.hostname = "#{username}SW"
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "#{username}SW"
      end
  
      worker.vm.box = "bento/debian-12"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provision "shell", path: "./scripts/agent.sh", args: ['192.168.56.110']
    end
  end
  