Vagrant.configure(2) do |config| 

    NODES = [
        { :hostname => "tariniS", :ip => "192.168.56.110", :cpus => "1", :mem => "1024", :type => "server"},
        { :hostname => "asekkakSW", :ip => "192.168.56.111", :cpus => "1", :mem => "1024", :type => "agent" }
    ]

    config.vm.box = "ubuntu/jammy64"

    NODES.each do |node|
        config.vm.define node[:hostname] do |cfg|
            cfg.vm.hostname = node[:hostname]
            cfg.vm.network "private_network", ip: node[:ip]

            cfg.vm.provider "virtualbox" do |v|
                v.customize ["modifyvm", :id, "--cpus", node[:cpus]]
                v.customize ["modifyvm", :id, "--memory", node[:mem]]
                v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
                v.customize ["modifyvm", :id, "--name", node[:hostname]]
            end

            cfg.vm.provision "shell", inline: "ethtool -K enp0s8 tx off rx off gso off gro off tso off", run: "always"

            if node[:type] == "server"
                cfg.vm.provision "shell", path: "scripts/install_k3s_server.sh"
            else
                cfg.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
            end
        end
    end
end